import Link from "next/link";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { db } from "@/lib/db";

export const metadata = {
  title: "Terms of Service - CourseMind",
  description: "CourseMind's terms of service and user agreement.",
};

async function getTermsOfService() {
  try {
    const policy = await db.policy.findUnique({
      where: { type: "terms" },
    });
    return policy;
  } catch (error) {
    console.error("Error fetching terms of service:", error);
    return null;
  }
}

const DEFAULT_CONTENT = `
<h2>1. Acceptance of Terms</h2>
<p>
  By accessing and using CourseMind ("the Service"), you accept and
  agree to be bound by these Terms of Service. If you do not agree to
  these terms, please do not use our Service.
</p>

<h2>2. Description of Service</h2>
<p>
  CourseMind provides AI-powered course generation and learning
  platform services. We use artificial intelligence to help users create
  educational content, take quizzes, and interact with an AI tutor.
</p>

<h2>3. User Accounts</h2>
<h3>3.1 Registration</h3>
<p>
  To use certain features, you must create an account. You agree to:
</p>
<ul>
  <li>Provide accurate, current information</li>
  <li>Maintain the security of your account</li>
  <li>Be responsible for all activities under your account</li>
  <li>Notify us immediately of unauthorized access</li>
</ul>

<h3>3.2 Age Requirements</h3>
<p>
  You must be at least 13 years old to use our Service. Users under 18
  must have parental or guardian consent.
</p>

<h2>4. Subscription Plans</h2>
<h3>4.1 Free Plan</h3>
<ul>
  <li>Up to 3 courses</li>
  <li>Basic features</li>
  <li>AI course generation</li>
  <li>Limited quiz questions</li>
</ul>

<h3>4.2 Pro Plans</h3>
<ul>
  <li><strong>Monthly Plan:</strong> $9.99/month</li>
  <li><strong>Yearly Plan:</strong> $99.99/year (save 17%)</li>
  <li>Up to 50 courses</li>
  <li>Unlimited quizzes</li>
  <li>AI tutor access</li>
  <li>Course sharing</li>
  <li>Certificate generation</li>
  <li>Priority support</li>
</ul>

<h3>4.3 Billing</h3>
<p>
  Subscriptions are billed automatically at the start of each billing
  period. You can cancel anytime. Cancellation takes effect at the end
  of the current billing period.
</p>

<h2>5. Refund Policy</h2>
<p>
  We offer refunds within 7 days of your initial purchase or renewal.
  To request a refund, contact support@coursemind.com with your order
  details. Refunds are processed within 5-10 business days.
</p>

<h2>6. Intellectual Property</h2>
<h3>6.1 Your Content</h3>
<p>
  You retain ownership of courses and content you create. By using our
  Service, you grant us a license to:
</p>
<ul>
  <li>Store and display your content</li>
  <li>Share public courses with other users</li>
  <li>Use anonymized data to improve our services</li>
</ul>

<h3>6.2 AI-Generated Content</h3>
<p>
  Content generated by our AI is provided "as is" without warranties.
  You are responsible for verifying the accuracy of AI-generated content
  before use. We do not guarantee the educational value or factual
  accuracy of AI-generated material.
</p>

<h3>6.3 Our Intellectual Property</h3>
<p>
  The Service, including its design, features, and underlying technology,
  is owned by CourseMind and protected by intellectual property laws.
</p>

<h2>7. Acceptable Use</h2>
<p>You agree NOT to:</p>
<ul>
  <li>Use the Service for illegal purposes</li>
  <li>Violate others' intellectual property rights</li>
  <li>Share explicit, harmful, or offensive content</li>
  <li>Attempt to hack, disrupt, or reverse engineer the Service</li>
  <li>Use automated tools to scrape or collect data</li>
  <li>Impersonate others or provide false information</li>
  <li>Spam or harass other users</li>
  <li>Sell, resell, or commercially exploit the Service</li>
</ul>

<h2>8. AI Content Disclaimer</h2>
<p>
  <strong>Important:</strong> AI-generated content may contain errors,
  inaccuracies, or biases. Always:
</p>
<ul>
  <li>Verify important information from authoritative sources</li>
  <li>Use AI content as a learning aid, not sole source of truth</li>
  <li>Apply critical thinking to AI-generated material</li>
  <li>Understand that AI may reflect biases from training data</li>
</ul>

<h2>9. Data and Privacy</h2>
<p>
  Your use of the Service is subject to our Privacy Policy. We collect
  and process data as described in the Privacy Policy. By using the
  Service, you consent to such collection and processing.
</p>

<h2>10. Third-Party Services</h2>
<p>
  We use third-party services including:
</p>
<ul>
  <li><strong>Stripe:</strong> Payment processing</li>
  <li><strong>Google Gemini AI:</strong> Course generation and tutoring</li>
  <li><strong>Vercel/AWS:</strong> Hosting and infrastructure</li>
</ul>
<p>
  Your use of these services is subject to their respective terms.
</p>

<h2>11. Termination</h2>
<p>
  We reserve the right to suspend or terminate your account if you:
</p>
<ul>
  <li>Violate these Terms of Service</li>
  <li>Engage in fraudulent or abusive behavior</li>
  <li>Create multiple accounts to bypass restrictions</li>
</ul>
<p>
  Upon termination, you lose access to your account and content. We may
  retain certain data as required by law.
</p>

<h2>12. Disclaimer of Warranties</h2>
<p>
  THE SERVICE IS PROVIDED "AS IS" WITHOUT WARRANTIES OF ANY KIND.
  WE DO NOT GUARANTEE:
</p>
<ul>
  <li>Uninterrupted or error-free operation</li>
  <li>Accuracy or reliability of content</li>
  <li>Educational outcomes or results</li>
  <li>Compatibility with all devices or browsers</li>
</ul>

<h2>13. Limitation of Liability</h2>
<p>
  TO THE MAXIMUM EXTENT PERMITTED BY LAW, COURSEMIND SHALL NOT BE LIABLE FOR:
</p>
<ul>
  <li>Indirect, incidental, or consequential damages</li>
  <li>Loss of profits, data, or goodwill</li>
  <li>Service interruptions or errors</li>
  <li>Third-party conduct or content</li>
</ul>
<p>
  Our total liability shall not exceed the amount you paid in the past 12 months.
</p>

<h2>14. Indemnification</h2>
<p>
  You agree to indemnify and hold harmless CourseMind from claims arising
  from your use of the Service, violation of these terms, or infringement
  of others' rights.
</p>

<h2>15. Changes to Terms</h2>
<p>
  We may modify these terms at any time. We will notify you of significant
  changes via email or through the Service. Continued use after changes
  constitutes acceptance of modified terms.
</p>

<h2>16. Governing Law</h2>
<p>
  These terms are governed by the laws of [Your Jurisdiction]. Any disputes
  shall be resolved in the courts of [Your Jurisdiction].
</p>

<h2>17. Contact Information</h2>
<p>
  For questions about these terms, contact us:
</p>
<ul>
  <li><strong>Email:</strong> legal@coursemind.com</li>
  <li><strong>Support:</strong> support@coursemind.com</li>
  <li><strong>Website:</strong> <a href="/contact">Contact Form</a></li>
</ul>

<p className="mt-8 text-sm">
  <em>
    These terms are effective as of January 1, 2025. By using CourseMind,
    you acknowledge that you have read, understood, and agree to be bound
    by these Terms of Service.
  </em>
</p>
`;

export default async function TermsPage() {
  const policy = await getTermsOfService();

  return (
    <div className="container mx-auto px-4 py-16 max-w-4xl">
        <h1 className="text-4xl font-bold mb-4">
          {policy?.title || "Terms of Service"}
        </h1>
        <p className="text-muted-foreground mb-8">
          Last updated: {policy?.updatedAt
            ? new Date(policy.updatedAt).toLocaleDateString("en-US", {
                year: "numeric",
                month: "long",
                day: "numeric",
              })
            : "January 1, 2025"}
        </p>

        <Card>
          <CardContent
            className="prose prose-gray dark:prose-invert max-w-none pt-6 prose-headings:font-bold prose-h2:text-2xl prose-h2:mt-8 prose-h2:mb-4 prose-h3:text-xl prose-h3:mt-6 prose-h3:mb-3 prose-p:mb-4 prose-ul:mb-4 prose-li:mb-2 whitespace-pre-line"
            dangerouslySetInnerHTML={{
              __html: policy?.content || DEFAULT_CONTENT,
            }}
          />
        </Card>

        {/* Footer Links */}
        <div className="mt-8 flex gap-6 text-sm text-muted-foreground">
          <Link href="/privacy" className="hover:text-foreground">
            Privacy Policy
          </Link>
          <Link href="/contact" className="hover:text-foreground">
            Contact Us
          </Link>
          <Link href="/about" className="hover:text-foreground">
            About Us
          </Link>
        </div>
    </div>
  );
}
