export const SUPPORTED_LANGUAGES = [
  "English",
  "Spanish",
  "French",
  "German",
  "Italian",
  "Portuguese",
  "Russian",
  "Chinese",
  "Japanese",
  "Korean",
  "Arabic",
  "Hindi",
  "Bengali",
  "Punjabi",
  "Urdu",
  "Indonesian",
  "Malay",
  "Thai",
  "Vietnamese",
  "Turkish",
  "Polish",
  "Ukrainian",
  "Romanian",
  "Dutch",
  "Greek",
  "Czech",
  "Swedish",
  "Hungarian",
  "Finnish",
  "Norwegian",
  "Danish",
  "Hebrew",
  "Tagalog",
  "Swahili",
  "Tamil",
  "Telugu",
  "Marathi",
  "Gujarati",
  "Kannada",
] as const;

export type SupportedLanguage = typeof SUPPORTED_LANGUAGES[number];
