import { notFound } from "next/navigation";
import { db } from "@/lib/db";
import { PolicyEditor } from "@/components/admin/policy-editor";

const POLICY_TYPES = {
  privacy: {
    title: "Privacy Policy",
    description: "Data protection and privacy practices",
    defaultContent: `# Privacy Policy

Last updated: ${new Date().toLocaleDateString()}

## Introduction

This Privacy Policy describes how CourseMind ("we", "our", or "us") collects, uses, and shares your personal information when you use our service.

## Information We Collect

### Account Information
- Name and email address
- Profile information
- Authentication data

### Usage Information
- Courses created and accessed
- Learning progress
- Quiz results and scores

### AI Interactions
- Course topics and generation requests
- Chat messages with AI tutor
- Quiz questions and answers

## How We Use Your Information

We use your information to:
- Provide and improve our services
- Generate personalized course content
- Track your learning progress
- Send important updates and notifications
- Respond to your inquiries

## Data Sharing

We do not sell your personal information. We may share data with:
- Service providers (hosting, AI services)
- Payment processors (Stripe)
- As required by law

## Data Security

We implement industry-standard security measures to protect your data.

## Your Rights

You have the right to:
- Access your personal data
- Correct inaccurate data
- Delete your account and data
- Export your data

## Contact Us

For privacy concerns, contact us at: privacy@coursemind.com`,
  },
  terms: {
    title: "Terms of Service",
    description: "Terms and conditions for using the service",
    defaultContent: `# Terms of Service

Last updated: ${new Date().toLocaleDateString()}

## 1. Acceptance of Terms

By accessing and using CourseMind, you accept and agree to be bound by these Terms of Service.

## 2. Description of Service

CourseMind is an AI-powered course generation platform that allows users to create, learn, and share educational content.

## 3. User Accounts

### 3.1 Registration
You must provide accurate information when creating an account.

### 3.2 Account Security
You are responsible for maintaining the security of your account credentials.

## 4. Subscription Plans

### 4.1 Free Plan
- Limited to 3 courses
- Basic features

### 4.2 Pro Plans
- Monthly: $9.99/month
- Yearly: $99.99/year
- Up to 50 courses
- Advanced features

### 4.3 Billing
Subscriptions are billed automatically. You can cancel anytime.

## 5. Refund Policy

Refunds are available within 7 days of purchase. Contact support@coursemind.com.

## 6. Intellectual Property

### 6.1 Your Content
You retain ownership of courses you create.

### 6.2 AI-Generated Content
Content generated by our AI is provided "as is" without warranties.

## 7. Acceptable Use

You agree not to:
- Use the service for illegal purposes
- Violate others' intellectual property rights
- Attempt to hack or disrupt the service
- Share explicit or harmful content

## 8. AI Content Disclaimer

AI-generated content may contain errors or inaccuracies. Always verify important information.

## 9. Termination

We reserve the right to suspend or terminate accounts that violate these terms.

## 10. Limitation of Liability

CourseMind is provided "as is" without warranties. We are not liable for indirect damages.

## 11. Changes to Terms

We may update these terms. Continued use constitutes acceptance of changes.

## 12. Contact

For questions about these terms, contact: legal@coursemind.com`,
  },
};

async function getPolicy(type: string) {
  const policy = await db.policy.findUnique({
    where: { type },
  });
  return policy;
}

export async function generateMetadata({ params }: { params: Promise<{ type: string }> }) {
  const { type } = await params;
  const policyType = POLICY_TYPES[type as keyof typeof POLICY_TYPES];

  if (!policyType) {
    return { title: "Policy Not Found" };
  }

  return {
    title: `Edit ${policyType.title} - Admin`,
  };
}

export default async function EditPolicyPage({
  params,
}: {
  params: Promise<{ type: string }>;
}) {
  const { type } = await params;
  const policyType = POLICY_TYPES[type as keyof typeof POLICY_TYPES];

  if (!policyType) {
    notFound();
  }

  const policy = await getPolicy(type);

  return (
    <div className="space-y-6">
      <div>
        <h2 className="text-3xl font-bold">{policyType.title}</h2>
        <p className="text-muted-foreground mt-2">
          {policyType.description}
        </p>
      </div>

      <PolicyEditor
        type={type}
        title={policyType.title}
        initialContent={policy?.content || policyType.defaultContent}
      />
    </div>
  );
}
